### ISSUE TITLE
Generic example

### ISSUE THREAD

**Issue by jspeckman** [mjcumming/homie4#1]
Do you have a generic example to create a device with multiple nodes and multiple properties per node?
What I want to do is create an 'air quality' device, that has nodes for pollution and allergens, with the levels of each made available through properties.

**Comment by mjcumming** [comment]
Have a look at this thermostat device

https://github.com/mjcumming/Somecomfort-Homie/blob/master/homie_device/device_honeywell_thermostat.py

**Comment by jspeckman** [comment]
Thanks!
That is exactly what I needed.
