### ISSUE TITLE
Issue related to Home Asisstant

### ISSUE THREAD

**Issue by klaudiusz223** [mjcumming/homie4#12]
There is an issue related to Home Asisstant in this line
https://github.com/mjcumming/homie4/blob/35766d84ad1cad524357d172c986a3b3751cff25/homie/device_base.py#L280

```
    self.publish_homeassistant()
TypeError: publish_homeassistant() missing 2 required positional arguments: 'hass_config' and 'hass_payload'
```
I don't know the purpose of this line. I don't use HA so I  removed this line to fix it

**Comment by mjcumming** [comment]
I will remove - this was test code that "leaked out"..
