### ISSUE TITLE
MQTT last will  doesn't work

### ISSUE THREAD

**Issue by klaudiusz223** [mjcumming/homie4#13]
LWT doesn't work because set_will is after connect function . According to MQTT specification  LWT can be set only in connection packet.  I tested this using mosquitto server.

**Comment by mjcumming** [comment]
That was something I was looking into but didn't find why it wasn't working. I'll work on a fix.

**Comment by mjcumming** [comment]
Fixed in 0.3.1. Let me know if it works for you.

**Comment by klaudiusz223** [comment]
Yes, it works now. Thank You!
