### ISSUE TITLE
DateTime format (Property_DateTime)

### ISSUE THREAD

**Issue by klaudiusz223** [mjcumming/homie4#14]
I think the date format should be changed to% Y-% m-% dT% H:% M:% S.% f (with "T") as suggested in the discussion https://github.com/homieiot/convention/issues/160. It's according to ISO8601

**Comment by mjcumming** [comment]
Agree, again, was hoping that the Homie maintainers would make a formal change to the spec. Do you want to do a PR and change it?

**Comment by mjcumming** [comment]
fix merged
