### ISSUE TITLE
[question] on_connect on_disconnect callbacks

### ISSUE THREAD

**Issue by fvoges** [mjcumming/homie4#17]
I'm using the [Pimoroni Automation HAT](https://shop.pimoroni.com/products/automation-hat), and I'd like to use its controllable `comms` LED to reflect the MQTT connection status.

Is there an easy way to get my code hooked into the connect/disconnect callbacks to update the LED status? I've done this using the paho MQTT library directly, but I don't see a way to do this with your homie library.

Thanks

**Comment by mjcumming** [comment]
see device_base.py - you could use the mqtt_on_connection method. Let me know if that works.

**Comment by mjcumming** [comment]
checking back in - did that work?

**Comment by fvoges** [comment]
I haven't had the time to look in to this properly. But looks like I can do what I need with it. I'll close this now. Thanks!
