### ISSUE TITLE
[question] MQTT reconnect - how does that work?

### ISSUE THREAD

**Issue by clmcavaney** [mjcumming/homie4#18]
G'day,
I have been trying to figure out how the library manages disconnects from the MQTT broker.
I have the situation where the client does get disconnected occasionally (long wireless run which sometimes drops) and I have the following messages:

> MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0xb62edbd0> None Connection refused - incorrect protocol version
> MQTT On Disconnect: Result Code 1
> MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0xb62edbd0> None Connection refused - incorrect protocol version
> MQTT On Disconnect: Result Code 1

I was trying to diagnose where the reconnect attempts are being carried out in the `homie_mqtt_client.py` code, but it isn't clear to me.

Aside from that, it is strange that the error message is "incorrect protocol version" as the version won't have changed between when it was successfully connected to when it reconnects.

Any pointers would be great.

Thanks and regards,
Christopher

**Comment by clmcavaney** [comment]
Actually, does it relate to the paho mqtt loop_start() mechanism?

**Comment by mjcumming** [comment]
@clmcavaney sorry for the delay - yes, reconnect should happen within the loop. I vaguely remember seeing that error but not sure what caused it or why it went away - maybe mqtt broker reboot.

Is the reconnect not working?

**Comment by clmcavaney** [comment]
Thanks @mjcumming - I did investigate a bit further.
I found that I didn't have the most recent mosquitto broker installed, and updated (which did restart it of course).  So I will see how that goes.
Yeah, the reconnect didn't appear to be working.
Will keep an eye on it.

The homie python code is pretty vanilla with regards to how it uses the Paho MQTT library, so it should be rock solid.  I just hadn't seen those connect error messages before, couldn't figure out why it would be complaining of a version issue.  There is something in the Paho code about trying v3.1.1 then dropping back to v3.1 (but Mosquitto handles both of those versions).  So I wonder if the update did fix something.  I am now running mosquitto version 1.6.8

**Comment by mattange** [comment]
hi - i am still seing that message and i am using mosquitto verison 1.6.12, with a docker image. I am running the code on a raspberry pi on wifi (so disconnection may actually happen) and the server is behind a reverse proxy.
I'll test again, but i am indeed not only getting that error initially, also what appears to be a follow-on error...
Any views? no other errors before or after!
Perhaps using connect_asyncio instead of connect in the client code?
I also have a couple of ideas to have TLS support (e.g. for standard system-wide certs for the server but would likely send a pull request). also if i manage to sort the below of course but... seems like it's common so i thought i'd shout out first


```
MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x766f25d0> None Connection refused - incorrect protocol version
MQTT On Disconnect: Result Code 1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mattange/venvs/sensor_bme680/lib/python3.7/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/mattange/venvs/sensor_bme680/lib/python3.7/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/mattange/venvs/sensor_bme680/lib/python3.7/site-packages/paho/mqtt/client.py", line 1201, in loop
    return self.loop_misc()
  File "/home/mattange/venvs/sensor_bme680/lib/python3.7/site-packages/paho/mqtt/client.py", line 1628, in loop_misc
    self._check_keepalive()
  File "/home/mattange/venvs/sensor_bme680/lib/python3.7/site-packages/paho/mqtt/client.py", line 2430, in _check_keepalive
    self._do_on_disconnect(rc)
  File "/home/mattange/venvs/sensor_bme680/lib/python3.7/site-packages/paho/mqtt/client.py", line 3360, in _do_on_disconnect
    self.on_disconnect(self, self._userdata, rc)
  File "/home/mattange/venvs/sensor_bme680/lib/python3.7/site-packages/homie/mqtt/paho_mqtt_client.py", line 143, in _on_disconnect
    MQTT_Base._on_disconnect(self, rc)
  File "/home/mattange/venvs/sensor_bme680/lib/python3.7/site-packages/homie/mqtt/mqtt_base.py", line 112, in _on_disconnect
    self.mqtt_connected(False)
TypeError: 'bool' object is not callable
```

**Comment by clmcavaney** [comment]
G'day Matteo,
My Mosquitto is now v1.6.12 too.  Not within a Docker container but same version as you.
I have several homie clients on a Raspberry PI and they all connect successfully.
The PI is running an older Raspbian (9.13 - stretch) and the Python 3 version is 3.5.3
The Homie version I have installed is 0.3.5
The Paho version is 1.5.0

Which version of Homie and Paho do you have installed?

Christopher

**Comment by mjcumming** [comment]
I think I found the code causing the error dump. But it doesn't explain your problem connecting.

Try restarting your broker. I'll work on fixing the other issue.

**Comment by mattange** [comment]
Hi Christopher and Michael (in order of responses!)
This is interesting...
The original error was with Python 3.7.3 (Raspbian standard) but on a virtual environment. These are the packages in the virtual env:
`Package       Version  
------------- ---------
bme680        1.0.5    
Homie4        0.3.6    
netifaces     0.10.9   
paho-mqtt     1.5.1    
pip           18.1     
pkg-resources 0.0.0    
setuptools    40.8.0   
smbus         1.1.post2`

I have tried downgrading paho-mqtt to 1.5.0 and i do NOT get the error dump anymore... but still the connection problem appears to be there:

`MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0x7673c5d0> None Connection refused - incorrect protocol version
MQTT On Disconnect: Result Code 1`

Will keep investigating - until i sort it - but clearly the version of paho-mqtt seems to have some relevance.
The version of Homie does not though, as i have downgraded to 0.3.5 and no diff on the disconnect.

Thanks all for your help so far anyway.

**Comment by mattange** [comment]
In fact - I found the error and it was entirely on my part as to the connection (although interestingly the error was about protocol and not user) --- basically my MQTT is with usernames and passwords on a few selected users (manual stuff) and in the settings i had keyword "USER" instead of "USERNAME". 
Michael - i shall send you shortly a pull request for a couple of easy changes to the code in a couple of places and they probably don't mess up with whatever changes are going to be done your end - thanks for your excellent effort on this and hopefully you find these changes useful to incorporate in your code.

**Comment by mjcumming** [comment]
Sounds good - thank you.

It would probably help to log the username and password used - would help diagnose the problem. I don't use any security on my MQTT stuff.....

**Comment by clmcavaney** [comment]
Interesting, I upgraded to:
Homie4==0.3.6
paho-mqtt==1.5.1

yesterday and I then observed the same situation as before.  No successful reconnection.

Once I downgraded to:
Homie4==0.3.4
paho-mqtt==1.5.0

it is reconnecting again after it looses connection.

I'm looking into it further too.

**Comment by mattange** [comment]
Hi 
can i ask whether any progress was made on the reconnection? I have things working now:
1) my sensor is attached to a raspberry pi that is on 24/7
2) it publishes to a broker that, however, is not on 24/7 for now... so once the broker goes offline, it appears the following morning the Raspberry Pi hosting the code does **not** reconnect automatically.

Views? has it got to do with the paho-mqtt version?

**Comment by clmcavaney** [comment]
G'day @mattange,
So, when I downgraded to Homie4 (v0.3.4) and paho-mqtt (v1.5.0) on a Raspbian v9.13 with Python3 (v3.5.3) everything came good again.
I too run a service on the Pi that is a one wire temperature sensor monitor.  There are 3 sensors on that one wire "network".
I also run another service on the same Pi that is monitoring a door.

I have a MQTT broker running on another server but the connection between the Pi and the server is over a wireless link that isn't 100% reliable.  So, when that drops, the connection to the MQTT broker dies.

With those versions above, I have found that both scripts are able to reconnect successfully.

I will get log messages like this:
```
Dec 15 12:28:55 pi-shed homie-python-w1thermsensor-thermometer.py[10346]: INFO:homie.device_base:Device MQTT Connected state is False
Dec 15 12:28:55 pi-shed homie-python-w1thermsensor-thermometer.py[10346]: WARNING:homie.mqtt.paho_mqtt_client:MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0xb62116f0> None Connection refused - incorrect protocol version
Dec 15 12:28:55 pi-shed homie-python-w1thermsensor-thermometer.py[10346]: WARNING:homie.mqtt.mqtt_base:MQTT On Disconnect: Result Code 1
Dec 15 12:28:56 pi-shed homie-python-w1thermsensor-thermometer.py[10346]: INFO:homie.device_base:Device MQTT Connected state is True
```
or
```
Dec 15 12:28:45 pi-shed door-check-gpiozero-homie.py[10402]: INFO:homie.device_base:Device MQTT Connected state is False
Dec 15 12:28:45 pi-shed door-check-gpiozero-homie.py[10402]: WARNING:homie.mqtt.paho_mqtt_client:MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0xb610ff30> None Connection refused - incorrect protocol version
Dec 15 12:28:45 pi-shed door-check-gpiozero-homie.py[10402]: WARNING:homie.mqtt.mqtt_base:MQTT On Disconnect: Result Code 1
Dec 15 12:28:45 pi-shed door-check-gpiozero-homie.py[10402]: WARNING:homie.mqtt.paho_mqtt_client:MQTT Unexpected disconnection  <paho.mqtt.client.Client object at 0xb610ff30> None Connection refused - incorrect protocol version
Dec 15 12:28:45 pi-shed door-check-gpiozero-homie.py[10402]: WARNING:homie.mqtt.mqtt_base:MQTT On Disconnect: Result Code 1
Dec 15 12:28:58 pi-shed door-check-gpiozero-homie.py[10402]: INFO:homie.device_base:Device MQTT Connected state is True
```

I wasn't able to diagnose why this didn't reconnect when I upgraded paho-mqtt and Homie4.  It would need some further investigation of the code differences to see what is going on.

Are you able to change versions?

Regards,
Christopher

**Comment by mattange** [comment]
hi - i have indeed tested and i am running in a virtual env.
I have standard python on Raspbian and i am using my own branched version of Homie from the latest version. 
So i can say with almost certainty my error is related somehow to Paho version as downgrading to 1.5.0 instead of 1.5.1 makes reconnection just work.
go figure....

**Comment by Itja** [comment]
At least for me, after applying the fix, reconnect seems to work. Can somebody verify?

**Comment by mattange** [comment]
Hi - I have just merged your pull request into my own fork and will give that a go. I had put a couple of extra additions and put in a pull request to the original, but nothing conflicting with your change.
Will let you know as soon as I can verify, in particular, looking for reconnection after MQTT server shutdown and - hours later - MQTT server back up while client remains online.

**Comment by klaudiusz223** [comment]
Hi, 
I can also confirm that this fix works for me. 
To simulate disconnecting, find clientid which your homie device uses to connect to the broker, and then connect to the broker with the same client id. 
For example 
`mosquitto_sub -i auto-56B1198A-EABF-6C0E-B663-8F654CD16488 -u user  -P pass -h localhost -t '#'`

But i have also noticed in logs that before applying this fix, homie device sometimes disconnected from the broker and there was no exception in
```
/homie/mqtt/mqtt_base.py", line 112, in _on_disconnect
    self.mqtt_connected(False) 
TypeError: 'bool' object is not callable
```
and also no reconnection.

**Comment by mjcumming** [comment]
line 112 should read

self.mqtt_connected = False

Fixed.

> Hi,
> I can also confirm that this fix works for me.
> To simulate disconnecting, find clientid which your homie device uses to connect to the broker, and then connect to the broker with the same client id.
> For example
> `mosquitto_sub -i auto-56B1198A-EABF-6C0E-B663-8F654CD16488 -u user -P pass -h localhost -t '#'`
> 
> But i have also noticed in logs that before applying this fix, homie device sometimes disconnected from the broker and there was no exception in
> 
> ```
> /homie/mqtt/mqtt_base.py", line 112, in _on_disconnect
>     self.mqtt_connected(False) 
> TypeError: 'bool' object is not callable
> ```
> 
> and also no reconnection.
