### ISSUE TITLE
Get node id

### ISSUE THREAD

**Issue by jspeckman** [mjcumming/homie4#2]
Is there a way to retrieve the node id from a topic programmatically?
I'm working on a project that uses dynamically generated nodes, so I'd like to either be able to pass the node id to set_value of the property, or be able to retrieve it from the called function, to be able to set the value to the correct variable based on the node id.

Is this possible, or is it easier to have the far end client (openhab) pass the node id as part of the value?

Thanks,
Jason

**Comment by mjcumming** [comment]
Not sure I understand your use case. Any properties you define will automatically catch their own set messages. You shouldn't need to do any work finding the node property. Unless I am missing something... :)

**Comment by jspeckman** [comment]
Here's an example of what I'm trying to do:

homie/icloud/node-person-a/location-cache
homie/icloud/node-person-b/location-cache

node-person-a & node-person-b are read from a config file and have nodes and properties generated at runtime.

When the set-value function is called, I need a way to set some variables that affect some internal logic for that node, ie turn off location caching for person-a.

Hopefully the above makes better sense, or maybe I'm over thinking it and there's an obvious way that I'm missing.

I've tried passing a variable that contains the node-id (person) to the set-value function, but it always contains the last person read from the config file.

Thanks.

**Comment by mjcumming** [comment]
Not sure I completely follow but from a property you can get the node containing it using self.node.

**Comment by jspeckman** [comment]
Ok.

Here's a section of code, hopefully this will clear things up better.
```
### Node/property creation section
iCloud = Device_Base(device_id='icloud-bridge', name='iCloud Homie Bridge', mqtt_settings=mqtt_config)
for node in node_config.items():
  ### node[0] contains the name of the person
  node_config[node[0]]['node'] = Node_Base(iCloud, node[0], node[0].title(), node[0])
  iCloud.add_node(node_config[node[0]]['node'])
  node_config[node[0]]['location_cache'] = Property_Enum(node_config[node[0]]['node'], id="locationcache", name="%s Location Cache" % (node[0].title()), data_format='ON,OFF', value=node_config[node[0]]['cachedLocation'], set_value = lambda value: location_cache_handler(node[0], value, tags=['Switch']))
  node_config[node[0]]['node'].add_property(node_config[node[0]]['location_cache'])

### location_cache_handler function
def location_cache_handler(node, value):
  print(node, value)
  ### variable used in icloud processing loop
  node_config[node]['cachedLocation'] = value
  ### homie property
  node_config[node]['location_cache'].value = value

```
In the above, passing node[0] to the function location_cache_handler() in set_value, node[0] is always the last value to be read in from the loop.  I can only guess that this has something to do with the lambda, which I will admit to never having used before.

Thanks.

**Comment by mjcumming** [comment]
Agree, it is the lambda - you don't have it setup correctly. You need to create the lambda before you assign it to the setvalue. And you don't supply the node to lambda and only the value. You use the node value in the lambda.

**Comment by mjcumming** [comment]
Are you trying to supply location data to OH from iCloud?

**Comment by jspeckman** [comment]
Thanks, I'll give that a try.
Yes.  I've used the icloud addon in the past, but got tired of it having SSL issues every couple of weeks, so I decided to write my own using python and mqtt.  While I can pick my way through java, I've never been able to figure out OH's build system, which is also the reason I'm migrating from the isy addon to your isy homie bridge.

**Comment by mjcumming** [comment]
Ok, if you have the code on github, I would be interested in working on it with you.

**Comment by jspeckman** [comment]
I do.
https://github.com/jspeckman/icloud_homie_bridge

Thanks!

**Comment by mjcumming** [comment]
Looking more at pyicloud - how will this work with 2 factor authorization after it times out? Do you have to reenter?

**Comment by jspeckman** [comment]
Currently yes, I re-run icloud_login.py when it times out.
I'm sure there's a better way to do it, but I haven't gotten that far yet.

**Comment by mjcumming** [comment]
i'll play around with this over the next week.

**Comment by jspeckman** [comment]
Great, thanks.
BTW, I've still not been able to get the lambda to work right.

**Comment by mjcumming** [comment]
I pulled your archive and reworked it.

See https://github.com/mjcumming/iCloud-Homie

This allows you to send the verification code for the account from the account homie device.

In keeping with the homie concept, each device is separate versus using a node to represent a device.

**Comment by jspeckman** [comment]
I've played around with your reworked version, made a few tweaks, and it seems to be working very well.

Tweaks include:
Added control node to the devices for
refresh timer property
location on/off property
location cache on/off property

Also allowed for multiple iCloud accounts.

Thanks!

**Comment by mjcumming** [comment]
Would you do a pull request and I'll merge it in to the repo.
