### ISSUE TITLE
SSL/TLS not supported

### ISSUE THREAD

**Issue by half-monkey** [mjcumming/homie4#24]
Hi,

I'm using MQTT over a network that has other stuff on it, and so have it configured with SSL.
I'll submit a pull request with a (very) rough/simple idea to get this working for the PAHO client shortly...

Dave

**Comment by half-monkey** [comment]
Should've looked at the existing pull requests first - sorry! I'll wait until that's made it into the master.

Dave

**Comment by mjcumming** [comment]
merged - let me know if that works
