### ISSUE TITLE
Possible to group basic devices into one device ?

### ISSUE THREAD

**Issue by ccandreva** [mjcumming/homie4#28]
This is a rather basic usage question I can't figure out: Is it possible to set up an class that contains 2 or more existing basic devices ?
Let's say an audio device that would contain a device_switch for power and a device_dimmer for volume ? Or does it have to be written from scratch as device_audio  with the add_node commands ?

**Comment by mjcumming** [comment]
There is no one way or a predetermined proper way to setup devices. So you can use your example above and use the 2 already created devices. Or make a new device combining what you need from the existing code.
