### ISSUE TITLE
please release version 0.1.8 with recent fixes.

### ISSUE THREAD

**Issue by maxberger** [mjcumming/homie4#4]
Property_Boolean uses the standard python string representations for booleans, which is True and False. Instead, it should always send the lowercase version (true and false)

https://homieiot.github.io/specification/#boolean

File: Property_Boolean.py

TODO: Implement get_payload_from_value to return the lower case strings

I can provide a push request if needed, let me know.

**Comment by mjcumming** [comment]
This should be fixed in the latest release.

See https://github.com/mjcumming/homie4/blob/master/homie/node/property/property_boolean.py

**Comment by maxberger** [comment]
Ah, i see. Unfortunately pypi still has the version from december, and is missing this fix which was commited in Jan.


https://pypi.org/project/Homie4/
 Homie4 0.1.7
Last released: Dec 27, 2019

So I'll change this to:
please release version 0.1.8 with recent fixes.

**Comment by mjcumming** [comment]
pypi updated to 0.1.8. Sorry for the confusion.

**Comment by maxberger** [comment]
Thanks!
