### ISSUE TITLE
Dimmer Percent as Decimal(Float) to support INT

### ISSUE THREAD

**Issue by patn03** [mjcumming/homie4#6]
Currently there is a bug with Home Assistant that doesn't allow remapping values on payloads and only supports integers for dimming. Does OpenHAB or other systems want this in decimal? If so would it be worth putting in a flag or option to determine format? Looking at Homie Convention, It doesn't look like it would support same property with different formats stored in MQTT.

 I currently have this fixed by removing the multiply and divide by 100 lines. Leaving dimming set to use 0-100 instead of 0.0-1.0.

I do feel decimals are better for fractions/percents but I think most home automation only use 0-100 or 0-255 integers for the devices.

https://github.com/mjcumming/homie4/blob/6338938c59e56d8ade4162bf23a75fa43405ab6a/homie/node/property/property_dimmer.py#L42

https://github.com/mjcumming/homie4/blob/6338938c59e56d8ade4162bf23a75fa43405ab6a/homie/node/property/property_dimmer.py#L48

**Comment by mjcumming** [comment]
I completely agree, I do not like the decimal convention at all, especially since the property uses % as a unit of measure. But this a Homie issue and we should probably take it up over there. The library here simply follows the spec.....

**Comment by mjcumming** [comment]
However, for your use case, it would be easy to adjust the value before sending to HA

**Comment by patn03** [comment]
I had read it before but might have missed something. Just to confirm your referring to this homie convention https://homieiot.github.io/specification/#

My questions are I didn't see anything mentioned about percents or dimming. I noticed the format explains percents but doesn't go into data types about percents. 

One other confusion (might be me :-) ) is the float datatype and using formats
Shouldn't the format be "0:1" or does float always indicate values under 1.0?
`homie/dimmer-XYZ/dimmer/dimmer b'0.0'
homie/dimmer-XYZ/dimmer/dimmer/$unit b'%'
homie/dimmer-XYZ/dimmer/dimmer/$datatype b'float'
homie/dimmer-XYZ/dimmer/dimmer/$format b'0:100'`

Sorry for all the trouble just trying to get a better understanding of this

**Comment by mjcumming** [comment]
Yes, that is the correct link to homie.  

The float data type is described in the spec. The format property describes allowed values for the float property.

The Unit property attribute is where the % is used. In my opinion, in this case the format should be 0:100 not 0:1. 

I don't like the way % is implemented and its being discussed on the homie github.

**Comment by patn03** [comment]
In the sense of IOT leaving Percents at the resolution (0.0-1.0) gives more precision and makes sense to me. I don't think there would be a good point in changing that with with Homie Convention as its correct. Its the right design choice for you to pick percent since different vendors are using their dimmer values. I think I'll build this project from the form the fork for the time being(until HASS data template bug is fixed) using INT range 0-100 representative of the percent since the resolution in Homie4(Dimmers) module is already rounding this off with round() function. Thanks for the insight and a great project!

**Comment by mjcumming** [comment]
FYI, the Homie spec has been corrected to use numbers 0-100 for 0 to 100%
