### ISSUE TITLE
set_auth_credentials  -> username_pw_set

### ISSUE THREAD

**Issue by klaudiusz223** [mjcumming/homie4#9]
There is a problem in this place.
Should it be username_pw_set instead set_auth_credentials ?
https://github.com/mjcumming/homie4/blob/b3c663b29b338c8910ebbc89773027ddf8c3f36e/homie/mqtt/paho_mqtt_client.py#L76

**Comment by mjcumming** [comment]
I had pulled that block of code from elsewhere but agree it looks incorrect as per https://pypi.org/project/paho-mqtt/  

Have you tried the change?

**Comment by klaudiusz223** [comment]
I tried the change and it worked for me. The change is coherent with this line in the same file https://github.com/mjcumming/homie4/blob/b3c663b29b338c8910ebbc89773027ddf8c3f36e/homie/mqtt/paho_mqtt_client.py#L50.
But I switched to V3 and didn't test this to much

**Comment by mjcumming** [comment]
I you do a PR I'll merge it

**Comment by mjcumming** [comment]
fixed
